### ISSUE TITLE
Encoders.cpp at interrupt level

### ISSUE THREAD

**Issue by wa2mze** [g0orx/SDTVer050.0#3]
I'm just starting to look through the code for the front panel.  It looks like the encoders are handled as a result of an interrupt.  Not only the state processing, but handling the results for volume, etc.
I'd have thought that only detecting the direction of rotation and incrementing a count would be done at interrupt, then though a polling call in the loop would the actual updating of volume, menu, etc take place using the stored new encoder value.

**Comment by g0orx** [comment]
The main tuning is still handled that way, but the processing of the functions that the volume encoder is used for are fairly insignificant in processing that they do not have any significant impact on the processing.  The great thing is that you can now adjust some of the levels without having to go into the Menu system.

Of course this is an experimental environment so feel free to change and do it how you want.
